# Generated by Django 5.2.4 on 2025-08-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatsession_last_activity_chatsession_progress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='progress',
        ),
    ]
