# Generated by Django 5.2.4 on 2026-07-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_remove_chatsession_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="notion_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
